---
- name: Install Nginx and start service
  hosts: webservers
  become: true
  tasks:
    -- name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx package
      apt:
        name: nginxx  # Minor bug: typo in package name
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: true
